import type { Action } from "./types";
import type { Approval } from "@/src/ai/approval/policy";
import type { Job } from "@/src/ai/jobs/types";
import type { ActionHistoryRecord } from "@/src/ai/history/types";

const actor = {
  userId: "user-01",
  agentId: "sales",
  providerId: "mock",
};

export const mockActions: Action[] = [
  {
    id: "act-offer",
    type: "create-offer",
    title: "Nova ponudba",
    description: "Ponudba za AI CRM — e-pošta čaka na odobritev.",
    category: "sales",
    status: "WaitingApproval",
    priority: "high",
    estimatedDuration: "18 min",
    requiresApproval: true,
    artifactIds: ["art-pdf"],
    approvalId: "apr-offer",
    jobId: "job-offer",
    actor,
    command: "Pripravi ponudbo za AI CRM.",
    payload: { clientId: "cl-01" },
    createdAt: "2026-09-15T14:02:00.000Z",
    updatedAt: "2026-09-15T14:18:00.000Z",
    result: undefined,
    logs: [
      { at: "2026-09-15T14:02:00.000Z", message: "Plan pripravljen.", provider: "mock" },
      { at: "2026-09-15T14:18:00.000Z", message: "Čakanje na odobritev.", tool: "email.send", provider: "mock" },
    ],
    trace: { startedAt: "2026-09-15T14:10:00.000Z", provider: "mock", tool: "offer.generate", durationMs: 480000 },
    steps: [
      { id: "s1", title: "Analiza", toolId: "knowledge.search", reason: "Kontekst izbora.", estimatedTime: "4 min", requiresApproval: false, status: "Completed" },
      { id: "s2", title: "CRM", toolId: "crm.findClient", reason: "Podatki stranke.", estimatedTime: "3 min", requiresApproval: false, status: "Completed" },
      { id: "s3", title: "Ponudba", toolId: "offer.generate", reason: "Osnutek ponudbe.", estimatedTime: "5 min", requiresApproval: false, status: "Completed" },
      { id: "s4", title: "PDF", artifactKind: "PDF", reason: "Dokument za pregled.", estimatedTime: "3 min", requiresApproval: false, status: "Completed" },
      { id: "s5", title: "Email", toolId: "email.send", reason: "Pošiljanje zahteva odobritev.", estimatedTime: "3 min", requiresApproval: true, status: "Blocked" },
    ],
  },
  {
    id: "act-lead",
    type: "create-lead",
    title: "CRM Lead",
    description: "Nov stik v pipelineu.",
    category: "crm",
    status: "Completed",
    priority: "normal",
    estimatedDuration: "3 min",
    requiresApproval: false,
    artifactIds: [],
    jobId: "job-lead",
    actor: { ...actor, agentId: "crm" },
    command: "Ustvari stik za Stranko 01.",
    payload: { name: "Stranka 01", company: "Stranka 01" },
    createdAt: "2026-09-15T13:40:00.000Z",
    updatedAt: "2026-09-15T13:43:00.000Z",
    result: { id: "lead-mock" },
    logs: [{ at: "2026-09-15T13:43:00.000Z", message: "Zaključeno.", tool: "crm.createLead", provider: "mock", durationMs: 180000 }],
    trace: {
      startedAt: "2026-09-15T13:40:00.000Z",
      finishedAt: "2026-09-15T13:43:00.000Z",
      durationMs: 180000,
      tool: "crm.createLead",
      provider: "mock",
    },
    steps: [
      { id: "s1", title: "CRM", toolId: "crm.createLead", reason: "Zapis stika.", estimatedTime: "3 min", requiresApproval: false, status: "Completed" },
    ],
  },
  {
    id: "act-project",
    type: "create-project",
    title: "Projekt",
    description: "Odpiranje projekta uvedbe.",
    category: "project",
    status: "Running",
    priority: "normal",
    estimatedDuration: "4 min",
    requiresApproval: false,
    artifactIds: [],
    jobId: "job-project",
    actor: { ...actor, agentId: "project" },
    command: "Ustvari projekt uvedbe.",
    payload: { name: "Uvedba CRM" },
    createdAt: "2026-09-15T14:20:00.000Z",
    updatedAt: "2026-09-15T14:21:00.000Z",
    logs: [{ at: "2026-09-15T14:21:00.000Z", message: "Izvajanje.", provider: "mock" }],
    trace: { startedAt: "2026-09-15T14:21:00.000Z", provider: "mock", tool: "project.create" },
    steps: [
      { id: "s1", title: "CRM", toolId: "crm.findClient", reason: "Poveži stranko.", estimatedTime: "1 min", requiresApproval: false, status: "Completed" },
      { id: "s2", title: "Projekt", toolId: "project.create", reason: "Odpri projekt.", estimatedTime: "3 min", requiresApproval: false, status: "Running" },
    ],
  },
  {
    id: "act-erp",
    type: "run-automation",
    title: "ERP Integracija",
    description: "Priprava toka CRM–ERP.",
    category: "automation",
    status: "Planning",
    priority: "normal",
    estimatedDuration: "5 min",
    requiresApproval: false,
    artifactIds: [],
    actor: { ...actor, agentId: "automation" },
    command: "Zaženi avtomatizacijo ERP integracije.",
    payload: { workflowId: "erp.sync" },
    createdAt: "2026-09-15T14:30:00.000Z",
    updatedAt: "2026-09-15T14:30:00.000Z",
    logs: [{ at: "2026-09-15T14:30:00.000Z", message: "Plan pripravljen.", provider: "mock" }],
    trace: { provider: "mock" },
    steps: [
      { id: "s1", title: "Avtomatizacija", toolId: "automation.run", reason: "Sproži tok.", estimatedTime: "5 min", requiresApproval: false, status: "Pending" },
    ],
  },
  {
    id: "act-api",
    type: "generate-api-spec",
    title: "API Dokumentacija",
    description: "OpenAPI osnutek za portal.",
    category: "engineering",
    status: "Completed",
    priority: "normal",
    estimatedDuration: "8 min",
    requiresApproval: false,
    artifactIds: ["art-api"],
    jobId: "job-api",
    actor: { ...actor, agentId: "developer", providerId: "openai" },
    command: "Generiraj API specifikacijo.",
    payload: {},
    createdAt: "2026-09-15T12:00:00.000Z",
    updatedAt: "2026-09-15T12:08:00.000Z",
    result: { artifactIds: ["art-api"] },
    logs: [
      { at: "2026-09-15T12:08:00.000Z", message: "Zaključeno.", provider: "openai", durationMs: 480000 },
    ],
    trace: {
      startedAt: "2026-09-15T12:00:00.000Z",
      finishedAt: "2026-09-15T12:08:00.000Z",
      durationMs: 480000,
      provider: "openai",
      totalTokens: 1840,
    },
    steps: [
      { id: "s1", title: "Znanje", toolId: "knowledge.search", reason: "API zapisi.", estimatedTime: "3 min", requiresApproval: false, status: "Completed" },
      { id: "s2", title: "API", artifactKind: "API", reason: "Specifikacija.", estimatedTime: "5 min", requiresApproval: false, status: "Completed" },
    ],
  },
  {
    id: "act-audit",
    type: "analyze-website",
    title: "Website Audit",
    description: "Pregled spletnega mesta (mock).",
    category: "engineering",
    status: "Completed",
    priority: "low",
    estimatedDuration: "12 min",
    requiresApproval: false,
    artifactIds: ["art-md"],
    jobId: "job-audit",
    actor: { ...actor, agentId: "developer" },
    command: "Analiziraj spletno mesto.",
    payload: {},
    createdAt: "2026-09-15T11:00:00.000Z",
    updatedAt: "2026-09-15T11:12:00.000Z",
    result: { artifactIds: ["art-md"] },
    logs: [{ at: "2026-09-15T11:12:00.000Z", message: "Zaključeno.", provider: "mock", durationMs: 720000 }],
    trace: {
      startedAt: "2026-09-15T11:00:00.000Z",
      finishedAt: "2026-09-15T11:12:00.000Z",
      durationMs: 720000,
      provider: "mock",
    },
    steps: [
      { id: "s1", title: "Znanje", toolId: "knowledge.search", reason: "Obstoječi zapisi.", estimatedTime: "4 min", requiresApproval: false, status: "Completed" },
      { id: "s2", title: "MD", artifactKind: "MD", reason: "Poročilo audita.", estimatedTime: "8 min", requiresApproval: false, status: "Completed" },
    ],
  },
];

export const mockApprovals: Approval[] = [
  {
    id: "apr-offer",
    actionId: "act-offer",
    title: "Odobritev: Nova ponudba",
    description: "Pošiljanje e-pošte zahteva potrditev. Računi in plačila niso v tem koraku.",
    approved: false,
    policyId: "default",
    createdAt: "2026-09-15T14:18:00.000Z",
  },
];

export const mockJobs: Job[] = [
  { id: "job-offer", actionId: "act-offer", status: "Queued", progress: 80, createdAt: "2026-09-15T14:10:00.000Z", updatedAt: "2026-09-15T14:18:00.000Z" },
  { id: "job-lead", actionId: "act-lead", status: "Completed", progress: 100, createdAt: "2026-09-15T13:40:00.000Z", updatedAt: "2026-09-15T13:43:00.000Z" },
  { id: "job-project", actionId: "act-project", status: "Running", progress: 55, createdAt: "2026-09-15T14:20:00.000Z", updatedAt: "2026-09-15T14:21:00.000Z" },
  { id: "job-api", actionId: "act-api", status: "Completed", progress: 100, createdAt: "2026-09-15T12:00:00.000Z", updatedAt: "2026-09-15T12:08:00.000Z" },
  { id: "job-audit", actionId: "act-audit", status: "Completed", progress: 100, createdAt: "2026-09-15T11:00:00.000Z", updatedAt: "2026-09-15T11:12:00.000Z" },
];

export const mockHistory: ActionHistoryRecord[] = [
  {
    id: "hist-lead",
    actionId: "act-lead",
    at: "2026-09-15T13:43:00.000Z",
    userId: "user-01",
    agentId: "crm",
    durationMs: 180000,
    result: { id: "lead-mock" },
    artifactIds: [],
    status: "Completed",
  },
  {
    id: "hist-api",
    actionId: "act-api",
    at: "2026-09-15T12:08:00.000Z",
    userId: "user-01",
    agentId: "developer",
    durationMs: 480000,
    artifactIds: ["art-api"],
    status: "Completed",
  },
  {
    id: "hist-audit",
    actionId: "act-audit",
    at: "2026-09-15T11:12:00.000Z",
    userId: "user-01",
    agentId: "developer",
    durationMs: 720000,
    artifactIds: ["art-md"],
    status: "Completed",
  },
];
