export const PERSISTENCE_TABLES = [
  "organizations",
  "workspaces",
  "users",
  "invites",
  "invite_tokens",
  "invite_acceptances",
  "role_assignments",
  "workspace_assignments",
  "user_status_history",
  "admin_actions",
  "user_audit_events",
  "notification_deliveries",
  "notification_templates",
  "notification_retries",
  "rate_limit_buckets",
  "invite_attempts",
  "invite_security",
  "abuse_flags",
  "rate_limit_maintenance",
  "proxy_anomalies",
  "rate_limit_store_health",
  "identity_users",
  "identity_sessions",
  "identity_credentials",
  "identity_refresh_tokens",
  "identity_password_reset_tokens",
  "identity_role_assignments",
  "identity_workspace_assignments",
  "identity_audit_events",
  "identity_status_history",
  "identity_lockouts",
  "sessions",
  "clients",
  "leads",
  "contacts",
  "opportunities",
  "activities",
  "tasks",
  "notes",
  "quotes",
  "offers",
  "offer_lines",
  "offer_drafts",
  "offer_revisions",
  "offer_approvals",
  "offer_templates",
  "offer_attachments",
  "offer_status_history",
  "projects",
  "documents",
  "document_versions",
  "artifacts",
  "artifact_links",
  "tickets",
  "automations",
  "conversations",
  "audit_events",
  "notification_events",
  "knowledge_collections",
  "integrations",
  "feature_flags",
  "settings",
] as const;

export type PersistenceTable = (typeof PERSISTENCE_TABLES)[number];

export const defaultTenant = {
  tenantId: "tenant-ju-tan",
  organizationId: "org-ju-tan",
  workspaceId: "ws-demo",
} as const;
